version: '3.8'

services:
  pedagogical-intervention-webservice:
    build: .
    # Si no desea construir localmente, elimine la línea 'build: .' y use sólo la imagen publicada.
    image: artierocks/pedagogical-intervention-webservice:0.26.0-RELEASE
    container_name: pedagogical-intervention-webservice
    ports:
      - "8080:8080"
    environment:
      # Use percentages instead of a fixed Xmx to avoid size errors
      - MAX_RAM_PERCENT=75
      - INIT_RAM_PERCENT=25
      - SPRING_PROFILES_ACTIVE=default
      # Asegura que el binario de Java esté disponible para /entrypoint.sh
      - JAVA_HOME=/opt/java/openjdk
      - PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
      - /tmp:/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: artie-network
    external: false
