# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: whelk-io/maven-settings-xml-action@v14
      name: Server Configuration
      with:
        githubServer: false,
        servers: '[{"id": "snapshot", "username": ${{ secrets.NEXUS_PREPROD_USERNAME }}, "password": ${{ secrets.NEXUS_PREPROD_PASSWORD }} }, {"id": "release", "username": ${{ secrets.NEXUS_PROD_USERNAME }}, "password": ${{ secrets.NEXUS_PROD_PASSWORD }} }]'
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Publish with Maven
      run: mvn deploy
